# Generated by Django 5.2.5 on 2025-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
